### PR TITLE
Thread: Allow multiple simultaneous connections

### LINKED ISSUE #14: Thread: The server should be able to handle multiple requests at the same time

### PR DESCRIPTION
**Pull request by rubencm**
I have removed client socket from globals, now each thread have his own client socket, so the server can manage multiple client sockets at the same time.

Fixes #14

### CODE REVIEW

**Comment by 0xTheProDev** [comment]
@rubencm Just for Contributing Guideline, can you add a short description with a signoff?

**Comment by rubencm** [comment]
You can check how it works by hardcoding a sleep in the php file or in the process.c, and doing multiple requests

**Comment by 0xTheProDev** [comment]
@rubencm I am already putting in test suits. The contribution standard of **Bytes Club** asks to put commit messages in the following form:
```
shortlog: commit title

commit description
Signed-off-by: Name <email>
```
Ref: doc

**Comment by rubencm** [comment]
Edit: ok, i see, you have merged it manually or something

**Comment by 0xTheProDev** [comment]
Yes, since I pulled your commit on my local machine, I merged it here. Good job :+1:

**Pull request closed without merging**
